### ISSUE TITLE
Problem with Ref Parameters

### ISSUE THREAD

**Issue by roend83** [channeladam/ChannelAdam.Wcf#1]
I am trying to implement this in one of my projects and ran into an issue.  I have a WCF service that contains a "ref" parameter.  The DisposableServiceChannelProxy class does not properly support this.  I debugged through the code and found a way to fix this, but when I tried to submit a PR it said that ChannelAdam.Core has been archived.  How do you suggest I go about fixing this?

**Comment by icnocop** [comment]
Hi!

Can you submit a PR to this repository ([ChannelAdam.Wcf](https://github.com/channeladam/ChannelAdam.Wcf))?

[DisposableServiceChannelProxy.cs](https://github.com/channeladam/ChannelAdam.Wcf/blob/master/src/ChannelAdam.Wcf/ServiceModel/Internal/DisposableServiceChannelProxy.cs) is in this repository.

Thanks! 😄

**Comment by roend83** [comment]
I can, but it will be hacky.  The actual change that I had to make was to DisposableRealProxy and DisposableObjectRealProxy.  I'll send a PR so you can see what I mean.

**Comment by channeladam** [comment]
Hi @roend83 .

I don't necessarily agree with the pattern of using ref parameters (not that anyone asked!), and I presume you are working on a legacy code base (because now Microsoft says for WCF developers to move to ASP.NET Core or gRPC for all new development)...

I have unarchived ChannelAdam.Core to allow you to submit the PR for review, if you insist you need ref. 

Cheers,
Adam

**Comment by roend83** [comment]
@channeladam totally agree with you about the ref parameters shouldn't be used, but this is a legacy codebase that won't be trivial to change.

I submitted a PR that has updates to this repo only.  Let me know if you'd prefer that we put this updates in ChannelAdam.Core and then update the reference here instead.  I think that's a better solution long term, but if this project is not going to be modified going forward then it may not matter.

**Comment by channeladam** [comment]
@roend83 Sorry for the delay...  I would prefer to put the update in ChannelAdam.Core.

Is the change to `DisposableObjectRealProxy.InvokeMethod()` to do:
` result = methodInfo.Invoke(onThis, methodCallMessage.Args);`
instead of:
` result = methodInfo.Invoke(onThis, methodCallMessage.InArgs);`

and `DisposableRealProxy.Invoke()` to do:
```
returnMessage = new ReturnMessage(
                                result,                                 // Operation result
                                methodCallMessage.Args,  // Out arguments
                                methodCallMessage.ArgCount,  // Out arguments count
                                methodCallMessage.LogicalCallContext,   // Call context
                                methodCallMessage);                     // Original message
```
instead of passing in null and 0 for the out arguments and count?

Is there anything other than that (I've only had a quick peek) ?

thanks

**Comment by roend83** [comment]
That's pretty close.  I'll send a PR later today.

**Comment by channeladam** [comment]
@roend83 I believe this works:  https://github.com/channeladam/ChannelAdam.Core/pull/2/files

**Comment by channeladam** [comment]
@roend83 please update your NuGet package to ChannelAdam.Core version 1.6.3 - it should now support ref parameters. Please confirm the issue is resolved.
